/**
 * Created by Eric on 11/1/2015.
 */

var app = angular.module("app", ['ui.slider']);

app.controller("Controller", function($scope){

});

app.directive('herscalculator', function($timeout){
    var calculatorController = function($scope){
        $scope.gas = 0;
        $scope.electricity = 0;
        $scope.water = 0;
        $scope.hersScore = 64;
        $scope.annualSavings = 0;
        $scope.percentageSavings = 0;
        $scope.monthlySavings = 0;

        $scope.$watchGroup(['gas', 'electricity', 'water', 'hersScore'], function(){
            total();
            calculateSavings();
        }, true);

        $scope.calculateSavings = calculateSavings;

        $scope.total = total;

        function total(){
            return $scope.gas + $scope.water + $scope.electricity;
        }

        function calculateSavings() {
            var anValue = total() * 12;
            var moneyBenefit = 0.00;
            var moneyBenefitMonth = 0.00;
            var interestBenefit = 0;
            var hersOffsetRatio = .02429;
            var delta = anValue - Math.round($scope.hersScore / hersOffsetRatio);
            if(delta > 0) {
                moneyBenefit = delta;
                moneyBenefitMonth = Math.round(moneyBenefit/12);
                interestBenefit = parseInt((delta/anValue)*100);
            }
            $scope.percentageSavings = interestBenefit;
            $scope.monthlySavings = moneyBenefitMonth;
            $scope.annualSavings = moneyBenefit;
        }
    };

   return {
       restrict: 'E',
       scope: {},
       controller: calculatorController,
       templateUrl: "calculator.html",
       link: function($scope, el){
           //because the handle is generated by jquery ui,
           //any elements that need to go inside need to be
           //placed there programatically after it is rendered
           $timeout(function(){ //wait for handle render to attach hers score
               $('.ui-slider-handle').append($("#hersScore"));
           }, 0);
           var slider = $("#slider");
           var demarcationWidth = 3;
           var demarcationIncrement = 10;
           var max = parseInt($(slider).attr("max"));
           var min = parseInt($(slider).attr("min"));
           slider.each(function(){
               var vals = max - min;

               for(var i = 0; i <= vals; i++){
                   var slider = $('#slider');
                   if(i % demarcationIncrement == 0) {
                       var label = $('<label>' + (i + min) + '</label>').css({"left" : (i / vals * 100) + '%', "top" : "-50%"});
                       $(slider).append(label);
                       if(i/demarcationIncrement <= (max/demarcationIncrement - 2)){
                           var demarcation = $('<div class="demarcation"></div>').css({
                               "float": "left",
                               "width": $(slider).width() / Math.floor(max / demarcationIncrement),
                               "height": "100%",
                               "border-right": demarcationWidth + "px white dotted"
                           });
                           $(slider).append(demarcation);
                       }
                   }
               }
           });

           $(window).resize(function(){
               $('.demarcation').width($('#slider').width() / Math.floor(max / demarcationIncrement) - demarcationWidth + "px")
           });
       }
   }
});



